database:
  type: mysql
  host: localhost
  port: 3306
  database: sauron
  user: root
  password: toor
rules:
  items-to-track:
    super-weapons:
      contains:
        - custom
        - OP
      materials:
        - DIAMOND_SWORD
        - DIAMOND_AXE
      flags:
        - HIDE_UNBREAKABLE
      unbreakable: true
      has_nbt:
        - yronusaTest
    capybara-armors:
      contains:
        - Capybara
      materials:
        - DIAMOND_HELMET
        - DIAMOND_LEGGINGS
      has_nbt:
        - capybaraArmor
  illegal-items:
    ruleA:
      materials:
        - DIAMOND_SWORD
      has_nbt:
        - ultraIllegalObject
settings:
  verbose-level: HIGH # Values: HIGH, MEDIUM, LOW, NONE
  automatic-inventory-updating:
    enabled: true
    delay-between-checks: 300
    delay-between-players: 2
    delay-between-items: 0.5
  save-item-data: false
  in-hand-update-interval: 10
  container-update-interval: 10
  track-stacked-items: false
  clear-stacked-items: true
messages:
  dupe-found-player: "§7* §cYour item has been flagged has duplicated, please contact an administrator."
  stacked-item-found-player: "§7* §cHaving such stacked item is illegal, please contact an administrator."
  blacklisted-item-found-player: "§7* §cThis item has been blacklisted, please contact an administrator."
  illegal-item-found-player: "§7* §cThis item is illegal, please contact an administrator."
  not-tracked: "§7* §cThis item is not tracked."
  commands:
    insufficient-permission: "§7* §cYou do not have the permission to use that command."
    refund:
      success: "§7* §aThe item has been successfully refunded."
    blacklist:
      success: "§7* §cThe item has been blacklisted."
    track:
      stacked: "§7* §cPlease unstack the item before tracking it."
      success: "§7* §aItem successfully tracked !"
      fail: "§7* §cAn error has occurred, please see console."
      empty: "§7* §cYou need to hold an item."
      already-tracked: "§7* §cThis item is already tracked."
    reload: "§7* §aPlugin successfully reloaded."
    help:
      - "§cCommands:"
      - ""
      - "§7* §c/sauron: §7Shows this menu."
      - ""
      - "§7* §c/sauron tracked: §7Shows the list of tracked items. (NOT YET ENABLED)"
      - ""
      - "§7* §c/sauron track: §7Start tracking the object you have in hands."
      - ""
      - "§7* §c/sauron refund: §7Blacklist the current item and gives you a clean version."
      - ""
      - "§7* §c/sauron crash: §7Shows the help of crashes handling command."
      - ""
      - "§7* §c/sauron stop: §7Stop or start tracked item's update for player. Can be used for debugging or to custom items."
      - ""

crash-handler:
  crashed: false
  oldest-item: "2024-06-13 10:59:26.0"