database:
  type: mysql
  host: localhost
  port: 3306
  database: ULTIMATE_TRACKER
  user: root
  password: toor
rules:
  ruleA:
    contains:
      - custom
      - OP
    materials:
      - DIAMOND_SWORD
    flags:
      - HIDE_UNBREAKABLE
    unbreakable: true
settings:
  delay: 10
  track-stacked-items: false
  clear-stacked-items: true
messages:
  dupe-found-player: "§7* §cYour item has been flagged has duplicated, please contact an administrator."
  stacked-item-player: "§7* §cHaving such stacked item is illegal, please contact an administrator."
  not-tracked: "§7* §cThis item is not tracked."
  commands:
    insufficient-permission: "§7* §cYou do not have the permission to use that command."
    refund:
      success: "§7* §aThe item has been successfully refunded."
    blacklist:
      success: "§7* §cThe item has been blacklisted."
    track:
      stacked: "§7* §cPlease unstack the item before tracking it."
      success: "§7* §aItem successfully tracked !"
      fail: "§7* §cAn error has occurred, please see console."
      empty: "§7* §cYou need to hold an item."
      already-tracked: "§7* §cThis item is already tracked."
    reload: "§7* §aPlugin successfully reloaded."
    help:
      - "§aCommands:"
      - ""
      - "§7* §a/ut: §7Show this menu."
      - ""
      - "§7* §a/ut list saved: §7Show the list of saved items."
      - "§7* §a/ut list tracked: §7Show the list of tracked items."
      - ""
      - "§7* §a/ut track: §7Start tracking the object you have in hands."
      - ""
      - "§7* §a/ut stop: §7Stop or start tracked item's update for player. Can be used for debugging or custom items edition."
      - ""